development:
  server: http://localhost:5984
  database: photoquest_development

test:
  server: http://localhost:5984
  database: photoquest_test

production:
  server: http://localhost:5984
  database: photoquest
