development:
  server: http://localhost:5984
  database: railsrumble_development

test:
  server: http://localhost:5984
  database: railsrumble_test

production:
  server: http://localhost:5984
  database: railsrumble
